name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ariane5.sln
    - name: Extract config
      run: 7z x ${{github.workspace}}\src\Ariane5.Tests\localconfig.7z -p'${{secrets.localconfig}}' -o${{github.workspace}}\src\Ariane5.Tests
    - name: Build
      run: dotnet build ariane5.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ariane5.sln -c Release --no-build --verbosity normal
    - name: Publish Ariane5 to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\Ariane5\Ariane5.csproj
        PACKAGE_NAME: Ariane5
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}
    - name: Publish Ariane5.Azure to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\Ariane5.Azure\Ariane5.Azure.csproj
        PACKAGE_NAME: Ariane5.Azure
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}
    - name: Publish Ariane5.Azure to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\Ariane5.Msmq\Ariane5.Msmq.csproj
        PACKAGE_NAME: Ariane5.Msmq
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}
    - name: Publish Ariane5 Standard to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\ArianeStandard\ArianeStandard.csproj
        PACKAGE_NAME: ArianeStandard
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}
    - name: Publish Ariane5.Azure Standard to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}\src\ArianeStandard.Azure\ArianeStandard.Azure.csproj
        PACKAGE_NAME: ArianeStandard.Azure
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}