name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest
    env:
      APP_SETTINGS: ${{secrets.APPSETTINGS_TEST}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ariane5.sln
    - shell: cmd
      run: |
        echo ${{env.APPSETTINGS_TEST}} > ${{github.workspace}}\src\Ariane5.Tests\bin\Release\net5.0\localconfig\appsettings.json
    - name: Build
      run: dotnet build ariane5.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ariane5.sln -c Release --no-build --verbosity normal
