name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ariane5.sln
    - name: Build
      run: dotnet build ariane5.sln --configuration Release --no-restore
    - name: Extract config
      run: 7z x ${{github.workspace}}\src\Ariane5.Tests\localconfig.7z -p'${{secrets.localconfig}}' -o${{github.workspace}}\src\Ariane5.Tests
    - name: Test
      run: dotnet test ariane5.sln -c Release --no-build --verbosity normal
